name: CI

on:
  push:
    paths:
      - 'k4niz/factreal/**'
  pull_request:
    paths:
      - 'k4niz/factreal/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: k4niz/factreal
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest -q
